server:
  port: 4000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-thanos?useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root3306
    driver-class-name: com.mysql.cj.jdbc.Driver